# Generated by Django 5.1.3 on 2024-12-03 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reference',
            old_name='id_type_of_reference',
            new_name='type_of_reference',
        ),
    ]
