# Generated by Django 5.1.3 on 2024-12-04 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_system', '0002_rename_id_type_of_reference_reference_type_of_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='references', to='crm_system.client'),
        ),
    ]
