# Generated by Django 5.1.3 on 2024-12-04 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_system', '0005_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visiting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visiting_date', models.DateField()),
                ('visiting_time', models.TimeField()),
                ('missed_date', models.DateField(blank=True, null=True)),
                ('rescheduled_date', models.DateField(blank=True, null=True)),
                ('rescheduled_time', models.TimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_system.child')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_system.client')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_system.employee')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_system.status')),
            ],
        ),
    ]
