# Generated by Django 5.1.3 on 2024-12-05 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_system', '0009_alter_status_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='visiting',
            unique_together={('visiting_date', 'visiting_time')},
        ),
    ]
